// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/api/callback.ts";
import * as $1 from "./routes/api/login.ts";
import * as $2 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/api/callback.ts": $0,
    "./routes/api/login.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
